repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: lncpipe
  description: Analysis of long non-coding RNAs from RNA-seq datasets
  author:
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
